### ISSUE TITLE
App crashes with ECONNREFUSED

### ISSUE THREAD

**Issue by aivus** [athombv/com.irobot.roomba980#18]
Hi. I'm using stable v1.0.1 version and from time to time i'm getting next crash.

```
events.js:183
throw er; // Unhandled 'error' event
^

Error: connect ECONNREFUSED 192.168.0.141:8883
at Object._errnoException (util.js:1022:11)
at _exceptionWithHostPort (util.js:1044:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

Exit code: 1
Exit signal: null
```

**Update: Getting same error in v1.0.3**

**Comment by aivus** [comment]
I'm still getting this with v1.0.2.

```
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
2018-09-04 09:08:38 [log] [ManagerDrivers] [roomba980] [0] Connection was lost, finding new robots.
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Found a Roomba: 192.168.0.141.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
Forcing a disconnect.
.stream exists; we're destroying it.
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Lost connection with 192.168.0.141: offline.
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Disconnecting from robot...
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Lost connection with 192.168.0.141: offline.
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Disconnecting from robot...
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Lost connection with 192.168.0.141: offline.
2018-09-04 09:08:39 [log] [ManagerDrivers] [roomba980] [0] Disconnecting from robot...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.0.141:8883
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

```

**Comment by aivus** [comment]
Hey @RobinBol.
Should I move this issue to https://github.com/athombv/homey/issues?

**Comment by RobinBol** [comment]
Yes please, thank you!

**Comment by aivus** [comment]
Done. https://github.com/athombv/homey/issues/2867
